version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8  # Używamy obrazu z Pythonem 3.8
    steps:
      - checkout  # Pobranie kodu z repozytorium
      - run:
          name: Instalacja zależności
          command: |
            python -m venv venv         # Utworzenie wirtualnego środowiska
            . venv/bin/activate         # Aktywacja środowiska
            pip install -U pip          # Aktualizacja pip
            pip install numpy pytest    # Instalacja numpy i pytest
      - run:
          name: Uruchomienie testów
          command: |
            . venv/bin/activate         # Aktywacja środowiska
            pytest                      # Uruchomienie testów

workflows:
  version: 2
  test_workflow:
    jobs:
      - test
